backbone: "CLIP-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 10

seed: 33
deterministic: True
gpu: 0
num_workers: 8
prec: "amp"

num_epochs: 10
batch_size: 32
micro_batch_size: 32
lr: 5e-4
weight_decay: 5e-4
momentum: 0.9
loss_type: "Focal"
classifier: "CosineClassifier"

full_tuning: True
partial: null

init_head: "text_feat"
test_ensemble: False