backbone: "CLIP-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 10

seed: 33
deterministic: True
gpu: 0
num_workers: 8
prec: "amp"

num_epochs: 64
batch_size: 32
micro_batch_size: 32
lr: 1e-4 # 1e-4 #0.01
weight_decay: 1e-4 #1e-4 #5e-4
momentum: 0.9
gcn_lr: 1e-3 # 1e-4 #0.01
gcn_weight_decay: 1e-4 #1e-4 #5e-4
gcn_momentum: 0.9
loss_type: "DBLoss"
classifier: "CosineClassifier"

full_tuning: False
bias_tuning: False
ln_tuning: False
vpt_shallow: False
vpt_deep: False
adapter: False
adaptformer: True
lora: False
ssf_attn: False
ssf_mlp: False
ssf_ln: False

init_head: "text_feat"
test_ensemble: True
expand: 24
is_gcn: False
in_features: 512
mid_features: 2048
n_ctx: 4
ctx_init: a photo of a
is_prompt_tuning: False
sparse_topk: 20
reweight_p: 0.2
T: 0.3
map_alpha: 0.5
map_beta: 0.1